<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "solr_universal_boost"
 *
 * Auto generated by Extension Builder 2013-12-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Solr Universal Boost',
	'description' => 'Adds the possibility to add boosting keywords to every indexed recordtype',
	'category' => 'plugin',
	'author' => 'Hans Höchtl',
	'author_email' => 'jhoechtl@gmail.com',
	'author_company' => 'Onedrop Solutions GmbH & Co. KG',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.2',
			'solr' => '3.0.0'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>